default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  port:

# charcoal
development:
  <<: *default
  host: localhost
  database: <%= ENV['SCRIBE_LOCAL_DATABASE'] %>
  username: <%= ENV['SCRIBE_LOCAL_USERNAME'] %>
  password: <%= ENV['SCRIBE_LOCAL_PASSWORD'] %>

production:
  <<: *default
  host:     <% ENV['SCRIBE_PRODUCTION_HOST'] %>
  database: <% ENV['SCRIBE_PRODUCTION_DATABASE'] %>
  username: <% ENV['SCRIBE_PRODUCTION_USERNAME'] %>
  password: <% ENV['SCRIBE_PRODUCTION_PASSWORD'] %>
