default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432

# charcoal
development:
  #<<: *default
  #host: localhost
  #database: <%= ENV['SCRIBE_LOCAL_DATABASE'] %>
  #username: <%= ENV['SCRIBE_LOCAL_USERNAME'] %>
  #password: <%= ENV['SCRIBE_LOCAL_PASSWORD'] %>
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/development.sqlite3

production:
  <<: *default
  host:     <% ENV['SCRIBE_PRODUCTION_HOST'] %>
  database: <% ENV['SCRIBE_PRODUCTION_DATABASE'] %>
  username: <% ENV['SCRIBE_PRODUCTION_USERNAME'] %>
  password: <% ENV['SCRIBE_PRODUCTION_PASSWORD'] %>
