default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

# cobalt
development:
  <<: *default
  database: d584rbf3tjucme
  username: dgcaxckbzefbfj
  password: bAW2jv3U1plNeM-8Z4QNCkpXmE

# charcoal
test:
  <<: *default
  database: ddt1k3mt5npnhv
  username: qwwkcxigqbrhnh
  password: fapVQa5FIgiLVHUh8asI0lgiU7

production:
  <<: *default
  database: deesdt01j1n9j1
  username: psymztnmxichpb
  password: GmepJtoN4vcxVhaJ6_99aIlCzz
